@startuml

abstract class Animator
class ValueAnimator
class AnimatorSet
class ObjectAnimator
class TimeAnimator
Animator <|-- AnimatorSet
Animator <|-- ValueAnimator
ValueAnimator <|-- ObjectAnimator
ValueAnimator <|-- TimeAnimator

@enduml